fc_logistic_regression:
  input:
    train: "client.csv"
    test: "client.csv"
  output:
    pred: "pred.csv"
    proba: "proba.csv"
    test: "test.csv"
  format:
    sep: ","
    label: "label"
  split:
    mode: "directory"
    dir: "test"
  algo:
    max_iterations: 10000